name: Build FRC iOS
on:
  #  Workflow dispatch
  workflow_dispatch:

jobs:
  build:
    name: Build and upload FRC iOS
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "macos-12"
            version: "14.2"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install ldid

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build SideStore
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: make fakesign

      - name: Convert to IPA
        run: make ipa

      - name: Upload SideStore.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: App.ipa
          path: App.ipa
